server:
  error:
    whitelabel:
      enabled: false
  port: 8081
spring:
  profiles:
    active: docker
  cache:
    type: redis
  config:
    import: classpath:secrets.yaml
  data:
    redis:
      repositories:
        enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          writetimeout: 5000
          connectiontimeout: 5000
          timeout: 5000
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: api-service
eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${random.value}}
  client:
    service-url:
      default-zone: http://eureka-discovery:8761/eureka/

logging:
  level:
    org.springframework.security: debug
    org.springframework.data.mongodb: debug
    org.springframework.data.redis: debug