server:
  port: 8081
  error:
    whitelabel:
      enabled: off
spring:
  profiles:
    active: docker
  cache:
    type: redis
  data:
    redis:
      repositories:
        enabled: false
  application:
    name: api-service