services: # not tested yet

  # EUREKA DISCOVERY
  eureka-discovery:
    build:
      context: eureka-discovery
      dockerfile: eureka-discovery/Dockerfile
    image: eureka-discovery:latest
    ports:
      - "8761:8761"
    networks:
      - marine-unit-monitoring-network

  #GATEWAY
  gateway:
    build:
      context: gateway
      dockerfile: gateway/Dockerfile
    image: gateway:latest
    ports:
      - "8011:8011"
    networks:
      - marine-unit-monitoring-network
    depends_on:
      - eureka-discovery
      - api-service
      - admin-service
      - dev-service

  # KEYCLOAK - todo
  keycloak:

  # API SERVICE
  api-service:
    build:
      context: api-service
      dockerfile: api-service/Dockerfile
    image: api-service:latest
    ports:
      - "8080:8080"
    networks:
      - marine-unit-monitoring-network
      - api-service-network
    depends_on:
      - eureka-discovery
      - api-service-mongodb-primary

  api-service-mongodb-primary:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - api-service-network
    depends_on:
      - api-service-mongodb2
      - api-service-mongodb3
    command:
      - bin/sh
      - -c
      - |
        /db-init/mongo-keyfile-init.sh
        mongod --replSet marine-unit-monitoring-db-rs --bind_ip_all
    volumes:
      - api-service/docker-deploy/db-init/:/db-init/
      - api-service-mongodb-primary-db

  api-service-mongodb2:
    image: mongo:latest
    ports:
      - "27027:27017"
    networks:
      - api-service-network
    command:
      - bin/sh
      - -c
      - |
        /db-init/mongo-keyfile-init.sh
        mongod --replSet marine-unit-monitoring-db-rs --bind_ip_all
    volumes:
      - api-service-mongodb2-db

  api-service-mongodb3:
    image: mongo:latest
    ports:
      - "27037:27017"
    networks:
      - api-service-network
    command:
      - bin/sh
      - -c
      - |
        /db-init/mongo-keyfile-init.sh
        mongod --replSet marine-unit-monitoring-db-rs --bind_ip_all
    volumes:
      - api-service-mongodb3-db

  # ADMIN SERVICE
  admin-service:
    build:
      context: admin-service
      dockerfile: admin-service/Dockerfile
    image: admin-service:latest
    ports:
      - "8081:8081"
    networks:
      - marine-unit-monitoring-network
      - admin-service-network
    depends_on:
      - eureka-discovery
      - admin-service-mongodb

  admin-service-mongodb:
    image: mongo:latest
    ports:
      - "27018:27018"
    networks:
      - admin-service-network
    volumes:
      - admin-service-mongodb-db

  # DEV SERVICE
  dev-service:
    build:
      context: dev-service
      dockerfile: dev-service/Dockerfile
    image: dev-service:latest
    ports:
      - "8082:8082"
    networks:
      - marine-unit-monitoring-network
      - dev-service-network
    depends_on:
      - eureka-discovery
      - dev-service-mongodb

  dev-service-mongodb:
    image: mongo:latest
    ports:
      - "27019:27019"
    networks:
      - dev-service-network
    volumes:
      - dev-service-mongodb-db

  # REDIS
  redis:
    image: redis:latest
    ports:
      - "6479:6479"
    volumes:
      - cache:/usr/cache
    networks:
      - api-service-network

volumes:
  api-service-mongodb-primary-db:
  api-service-mongodb2-db:
  api-service-mongodb3-db:
  admin-service-mongodb-db:
  dev-service-mongodb-db:
  cache:
networks:
  marine-unit-monitoring-network:
  api-service-network:
  admin-service-network:
  dev-service-network: