token-url: http://keycloak.pl:8080/realms/marine-unit-monitoring-master/protocol/openid-connect/token
client-id: protection-service-client
client-secret: NfRXeBKAv4NCy3klk3XHAUDkSn4W4kha
protection-service-url: http://protection-service:8085/v1/ip-login-protection/rpc/protect-login