tokenUrl: http://keycloak.pl:8080/realms/marine-unit-monitoring-master/protocol/openid-connect/token
clientId: protection-service-client
clientSecret: NfRXeBKAv4NCy3klk3XHAUDkSn4W4kha
protectionServiceUrl: http://protection-service:8085/v1/ip-login-protection/rpc/protect-login