mum-commons:
  core:
    exception-handling:
      enabled: true
      type: servlet
  email-integration:
    enabled: true
    email-service-url: http://email-service:8084
  global-idm-service:
    type: servlet
    auth-conversion:
      keycloak-client-id: dev-service-client
    keycloak:
      enabled: true
      server-url: http://keycloak.pl:8080
      realm-name: marine-unit-monitoring-master
      client-id: dev-service-client
      client-secret: ${keycloak.client-secret}
logging:
  level:
    root: debug
spring:
  config:
    import: classpath:secrets.yaml
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      database: devServiceDB
      uri: mongodb://dev-service-mongodb-primary/${spring.data.mongodb.database}?replicaSet=devServiceDBRS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.pl:8080/realms/marine-unit-monitoring-master
          jwk-set-uri: http://keycloak.pl:8080/realms/marine-unit-monitoring-master/protocol/openid-connect/certs