server:
  port: 8083
  error:
    whitelabel:
      enabled: off
spring:
  cache:
    type: redis
  application:
    name: dev-service
  profiles:
    active: docker
  data:
    redis:
      repositories:
        enabled: false