jwt-granted-authority-converter:
  type: servlet
global-idm-service:
  type: servlet
  keycloak:
    server-url: http://keycloak:8080
    realm-name: mum-envelope-system-master
    client-id: developer-service-client
    client-secret: ${keycloak.client-secret}
spring:
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      database: devServiceDB
      uri: mongodb://dev-service-mongodb/${spring.data.mongodb.database}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/mum-envelope-system-master
          jwk-set-uri: http://keycloak:8080/realms/mum-envelope-system-master/protocol/openid-connect/certs