mum-microservice-commons:
  auth-conversion:
    type: servlet
  global-idm-service:
    type: servlet
    keycloak:
      server-url: http://keycloak:8080
      realm-name: marine-unit-monitoring-master
      client-id: developer-service-client
      client-secret: ${keycloak.client-secret}
  exception-handling:
    type: servlet
logging:
  level:
    root: debug
spring:
  config:
    import: classpath:secrets.yaml
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      database: devServiceDB
      uri: mongodb://dev-service-mongodb/${spring.data.mongodb.database}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/marine-unit-monitoring-master
          jwk-set-uri: http://keycloak:8080/realms/marine-unit-monitoring-master/protocol/openid-connect/certs