server:
  port: 8083
spring:
  application:
    name: dev-service
  profiles:
    active: docker
eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${random.value}}
  client:
    service-url:
      default-zone: http://eureka-discovery:8761/eureka/