server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      enabled: true

eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${random.value}}
  client:
    service-url:
      default-zone: http://eureka-discovery:8761/eureka/