server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}}
    hostname: gateway
  client:
    service-url:
      defaultZone: http://eureka-discovery:8761/eureka/