server:
  port: 8082
spring:
  application:
    name: admin-service
  profiles:
    active: docker
eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${random.value}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/