server:
  port: 8082
spring:
  application:
    name: admin-service
  profiles:
    active: docker
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}}
    hostname: admin-service
  client:
    service-url:
      defaultZone: http://eureka-discovery:8761/eureka/