keycloak-idm-service:
  server-url: http://localhost:8080
  realm-name: mum-api-envelope-system-master
  client-id: admin-service-server-superadmin
  client-secret: BkaBljk9xOEBD6k4ZsoLLCYinERVSJJI
logging:
  level:
    root: debug
spring:
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      database: adminServiceDB
      uri: mongodb://admin-service-mongodb/${spring.data.mongodb.database}