mum-microservice-commons:
  auth-conversion:
    type: servlet
  global-idm-service:
    type: servlet
    keycloak:
      server-url: http://keycloak:8080
      realm-name: mum-envelope-system-master
      client-id: admin-service-client
      client-secret: ${keycloak.client-secret}
logging:
  level:
    root: debug
spring:
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      database: adminServiceDB
      uri: mongodb://admin-service-mongodb/${spring.data.mongodb.database}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/mum-envelope-system-master
          jwk-set-uri: http://keycloak:8080/realms/mum-envelope-system-master/protocol/openid-connect/certs