jwt-granted-authority-converter:
  type: servlet
keycloak-idm-service:
  type: servlet
  server-url: http://keycloak:8080
  realm-name: mum-master
  client-id: admin-service-server-superadmin
  client-secret: BkaBljk9xOEBD6k4ZsoLLCYinERVSJJI
logging:
  level:
    root: debug
spring:
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      database: adminServiceDB
      uri: mongodb://admin-service-mongodb/${spring.data.mongodb.database}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/mum-master
          jwk-set-uri: http://keycloak:8080/realms/mum-master/protocol/openid-connect/certs