server:
  port: 8761
spring:
  application:
    name: eureka-discovery
eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${random.value}}
  client:
    fetch-registry: false
    register-with-eureka: false